### ISSUE TITLE
Duty Cycle?

### ISSUE THREAD

**Issue by lolren** [dpwe/FreqCountRP2#1]
Can you also add a duty cycle feature?

**Comment by dpwe** [comment]
Let me check what you're asking about: You have an external periodic pulse source.  You can use the FreqCountRP2 code to count the number of pulses in a fixed interval, so for instance if you count the number of pulses in a second, you get the pulse frequency.

But you also (or maybe only) want to measure the duty cycle, e.g. the PWM level, of this pulse train?  This is orthogonal to the pulse frequency, but is also an important attribute of the pulse train.

The FreqCountRP2 code is not a great place for such a function.  Here, I'm using the RP2's PWM counters to increment once per input edge, over some measuring interval. To measure duty cycle, you'd want the counters to free-run at the system clock rate (as they usually do), then compare their values at successive rising, falling, and rising edges.  Because of the different clocking of the PWM counter, you can't do this at the same time as the frequency counting (or at least not with the same PWM channel).

As it happens, the RP2 PWM example code includes code to measure duty cycle using the PWM subsystem; see here:
https://github.com/raspberrypi/pico-examples/blob/master/pwm/measure_duty_cycle/measure_duty_cycle.c

That code ought to get you going, although it's not a neatly-packaged library.

Good luck!

  DAn.
